version: "3.9"
services:
  stock_codes:
    image: node:14
    volumes:
      - /mnt/efs/market_feed/codes_spliter:/app
    ports:
      - "3333:80"
    dns: 8.8.8.8
    working_dir: /app
    entrypoint: [ "node", "dist/index.js" ]
    environment:
      MASTER_API: "https://dev-api.myspec.io/v2/investments/stocks/master"
      MASTER_API_KEY: "HCdRdFEVus3FY0jUBqvEU7bQEdrBgTjy74Sfx8Qb"
      PORT: 80
    depends_on:
      - redis
  tr_connect:
    image: node:14
    deploy:
      replicas: 10
    volumes:
      - /mnt/efs/market_feed/tr_connector:/app
    working_dir: /app
    entrypoint: ["node", "server.js"]
    environment:
      TR_SERVER: dev-tr.myspec.io
      TR_PORT: 5001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: spec12!@
      STOCK_CODE_URL: http://stock_codes/stocks/codes
      SERVER_ID: '{{.Task.Slot}}'
      REPLICAS: 10  # deploy.replicas 와 일치하는 값 설정 필요
    depends_on:
      - redis
      - stock_codes
  feed_publisher:
    image: node:14
    deploy:
      replicas: 1
    ports:
      - "3001:3001"
    volumes:
      - /mnt/efs/market_feed/feed_publisher:/app
    working_dir: /app
    entrypoint: [ "node", "feed_publisher.js" ]
    environment:
      SERVER_PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: spec12!@
      JWT_KEY: SpecRestApiSecretKey20211122
    depends_on:
      - redis
  redis:
    image: redis
    volumes:
      - /mnt/efs/market_feed/redis:/usr/local/etc/redis
    ports:
      - "7379:6379"
    dns: 8.8.8.8
    environment:
      TZ: Asia/Seoul